# Prevent Jekyll from processing anything – we just serve static files.
title: Music Tutors of Sydney
description: "Unlock your musical potential with expert lessons for all ages and skill levels."
url: "https://musictutorssydney.com" # Update to your custom domain if needed
baseurl: "" # Leave blank for root

# GitHub Pages settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination settings
paginate: 10
paginate_path: "/articles/page:num/"

# Exclude these files from build
exclude:
  - node_modules
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock